version: '3.9'

services:
  mysql:
    image: mysql:8.0.33
    container_name: agenticcp-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: agenticcp
      MYSQL_USER: agenticcp
      MYSQL_PASSWORD: agenticcppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - agenticcp-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agenticcp-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/agenticcp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: agenticcp
      SPRING_DATASOURCE_PASSWORD: agenticcppassword
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - agenticcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: agenticcp-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: agenticcp
      PMA_PASSWORD: agenticcppassword
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - agenticcp-network

volumes:
  mysql_data:

networks:
  agenticcp-network:
    driver: bridge
