spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agenticcp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: agenticcp
    password: agenticcppassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
  
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN
  
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

logging:
app:
  redis:
    enabled: ${APP_REDIS_ENABLED:true}
  level:
    root: INFO
    com.agenticcp.core: DEBUG
    org.springframework.web: INFO
    org.springframework.security: WARN

# 로컬 개발용 암호화 키 (개발 전용, 운영/형상 반출 금지)
config:
  cipher:
    key: ${CONFIG_CIPHER_KEY:MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA=}
    # 선택: 키 회전용 보조 키
    # secondaryKey: ${CONFIG_CIPHER_SECONDARY_KEY:}
    # 키 누락 시 동작 방침(FAIL/READ_ONLY). 기본 FAIL.
    # missingKeyBehavior: FAIL

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    displayRequestDuration: true
    displayOperationId: true
    showExtensions: true
    showCommonExtensions: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    docExpansion: list
    filter: true
    showRequestHeaders: true
    persistAuthorization: true
    layout: StandaloneLayout
    deepLinking: true
    supportedSubmitMethods: ["get", "post", "put", "delete", "patch"]
