spring:
  application:
    name: agenticcp-core
  
  profiles:
    active: local
  
  # 기본 프로필에서는 데이터소스 설정을 두지 않음 (프로필별로 분리)
    
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# JWT 설정
jwt:
  secret: ${JWT_SECRET:dGhpc2lzdGVzdGp3dHNlY3JldGtleWZvcmFnZW50aWNjcGNvcmVhcHBsaWNhdGlvbg==}
  access-token-expiration: 3600000 # 1시간 (밀리초)
  refresh-token-expiration: 604800000 # 7일 (밀리초)

# Redis 설정 (기본 비활성화, 프로필에서 활성화)
redis:
  enabled: false

logging:
  level:
    com.agenticcp: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/agenticcp-core.log

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/agenticcp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: agenticcp
    password: agenticcppassword

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/agenticcp}
    username: ${DATABASE_USERNAME:agenticcp}
    password: ${DATABASE_PASSWORD:agenticcppassword}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.agenticcp: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
