name: Epic
description: 대형 기능 영역을 정의하는 Epic 이슈
title: '[EPIC] '
labels: ['epic', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 📋 Epic 개요

        ### Epic 제목
        <!-- Epic의 제목을 명확하게 작성하세요 -->

        ### 비즈니스 목표
        <!-- 이 Epic이 달성하고자 하는 비즈니스 목표를 설명하세요 -->

        ### 포함할 UserStory 목록
        <!-- 이 Epic에 포함될 UserStory들을 나열하세요 -->
        - [ ] UserStory 1: 
        - [ ] UserStory 2: 
        - [ ] UserStory 3: 

        ## 🎯 성공 기준

        ### 기능적 요구사항
        - [ ] 
        - [ ] 
        - [ ] 

        ### 비기능적 요구사항
        - [ ] 
        - [ ] 
        - [ ] 

        ## 📊 추정 및 일정

        ### 예상 Story Point
        - [ ] 1-5 SP (소규모)
        - [ ] 6-13 SP (중간)
        - [ ] 14-21 SP (대규모)
        - [ ] 21+ SP (매우 대규모 - 분할 필요)

        ### 예상 완료 일정
        <!-- 예상 완료 일정을 작성하세요 -->

        ### 우선순위
        - [ ] 높음 (P0)
        - [ ] 중간 (P1)
        - [ ] 낮음 (P2)

        ## 🔗 관련 이슈

        ### 상위 Epic
        <!-- 상위 Epic이 있다면 링크하세요 -->

        ### 관련 Epic
        <!-- 관련된 다른 Epic들을 링크하세요 -->

        ### 참고 문서
        <!-- 관련 문서나 스펙을 링크하세요 -->

        ## 📝 추가 정보

        ### 제약사항
        <!-- 기술적, 비즈니스적 제약사항이 있다면 작성하세요 -->

        ### 리스크
        <!-- 예상되는 리스크와 대응 방안을 작성하세요 -->

        ### 의존성
        <!-- 다른 Epic이나 외부 의존성이 있다면 작성하세요 -->