name: Task
about: Feature를 구현하기 위한 구체적인 개발 작업을 정의하는 Task 이슈
title: '[TASK] '
labels: ['task', 'needs-triage']
assignees: ''
---

## 📋 Task 개요

### 상위 Feature
<!-- 이 Task가 속한 Feature를 링크하세요 -->
- Feature: #

### Task 제목
<!-- Task의 제목을 명확하게 작성하세요 -->

### Task 설명
<!-- Task에 대한 상세한 설명을 작성하세요 -->

## 🎯 작업 요구사항

### 구체적인 작업 내용
- [ ] 
- [ ] 
- [ ] 

### 구현할 파일/클래스
<!-- 구현하거나 수정할 파일들을 나열하세요 -->
- [ ] `src/main/java/.../Controller.java`
- [ ] `src/main/java/.../Service.java`
- [ ] `src/main/java/.../Repository.java`
- [ ] `src/main/java/.../Entity.java`
- [ ] `src/main/java/.../DTO.java`
- [ ] `src/test/java/.../Test.java`

### API 엔드포인트
<!-- 구현할 API 엔드포인트를 작성하세요 -->
- [ ] `GET /api/...` - 
- [ ] `POST /api/...` - 
- [ ] `PUT /api/...` - 
- [ ] `DELETE /api/...` - 

## 🔧 기술적 구현 세부사항

### 사용할 기술
- [ ] Spring Boot
- [ ] Spring Data JPA
- [ ] Spring Security
- [ ] AWS SDK
- [ ] 기타: 

### 구현 방법
<!-- 구체적인 구현 방법을 설명하세요 -->

### 코드 예시
```java
// 구현할 코드의 예시를 작성하세요
```

## 📊 추정 및 일정

### 예상 작업 시간
- [ ] 30분-1시간
- [ ] 1-2시간
- [ ] 2-4시간
- [ ] 4-8시간
- [ ] 1-2일

### 우선순위
- [ ] 높음 (P0)
- [ ] 중간 (P1)
- [ ] 낮음 (P2)

### 예상 완료 일정
<!-- 예상 완료 일정을 작성하세요 -->

## 🧪 테스트 계획

### 단위 테스트
- [ ] 메서드별 테스트
- [ ] 예외 상황 테스트
- [ ] 경계값 테스트

### 통합 테스트
- [ ] API 테스트
- [ ] 데이터베이스 테스트
- [ ] 외부 서비스 테스트

### 테스트 케이스
```java
@Test
public void testMethodName() {
    // Given
    // When
    // Then
}
```

## 🔗 관련 이슈

### 상위 Feature
<!-- 상위 Feature를 링크하세요 -->

### 관련 Task
<!-- 관련된 다른 Task들을 링크하세요 -->

### 의존성
<!-- 다른 Task나 외부 의존성이 있다면 작성하세요 -->

### 참고 문서
<!-- 관련 문서나 스펙을 링크하세요 -->

## 📝 추가 정보

### 제약사항
<!-- 기술적, 비즈니스적 제약사항이 있다면 작성하세요 -->

### 리스크
<!-- 예상되는 리스크와 대응 방안을 작성하세요 -->

### 성능 고려사항
<!-- 성능 관련 고려사항이 있다면 작성하세요 -->

### 보안 고려사항
<!-- 보안 관련 고려사항이 있다면 작성하세요 -->

### 코드 리뷰 포인트
<!-- 코드 리뷰 시 중점적으로 확인할 사항들을 작성하세요 -->

### 비고
<!-- 기타 참고사항이 있다면 작성하세요 -->
